### ISSUE TITLE
runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by hugochinchilla** [mariadb-corporation/replication-manager#39]
When following the instructions in the [contrib/cluster-maxscale/README.md](/mariadb-corporation/replication-manager/blob/0.7/contrib/cluster-maxscale/README.md) file I get this error after all the other services have been started.
~~~
panic: runtime error: makeslice: len out of range
replication-manager_1  | 
replication-manager_1  | goroutine 1 [running]:
replication-manager_1  | panic(0x972cc0, 0xc820278d20)
replication-manager_1  | 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
replication-manager_1  | main.glob.func10(0xcf9460, 0xc820084c80, 0x0, 0x5)
replication-manager_1  | 	/go/src/replication-manager/repmgr.go:220 +0x35e
replication-manager_1  | replication-manager/vendor/github.com/spf13/cobra.(*Command).execute(0xcf9460, 0xc820084b40, 0x5, 0x5, 0x0, 0x0)
replication-manager_1  | 	/go/src/replication-manager/vendor/github.com/spf13/cobra/command.go:565 +0x85a
replication-manager_1  | replication-manager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xcf8860, 0xcf9460, 0x0, 0x0)
replication-manager_1  | 	/go/src/replication-manager/vendor/github.com/spf13/cobra/command.go:651 +0x55c
replication-manager_1  | replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0xcf8860, 0x0, 0x0)
replication-manager_1  | 	/go/src/replication-manager/vendor/github.com/spf13/cobra/command.go:610 +0x2d
replication-manager_1  | main.main()
replication-manager_1  | 	/go/src/replication-manager/main.go:30 +0x27
~~~

~~~
$ docker-compose ps                                                                                                                                                                                         Name                               Command               State             Ports          
---------------------------------------------------------------------------------------------------------
clustermaxscale_agent1_1                replication-manager agent  ...   Up                               
clustermaxscale_agent2_1                replication-manager agent  ...   Up                               
clustermaxscale_agent3_1                replication-manager agent  ...   Up                               
clustermaxscale_mariadb1_1              docker-entrypoint.sh --log ...   Up       3306/tcp                
clustermaxscale_mariadb2_1              docker-entrypoint.sh --log ...   Up       3306/tcp                
clustermaxscale_mariadb3_1              docker-entrypoint.sh --log ...   Up       3306/tcp                
clustermaxscale_maxscale_1              /usr/bin/maxscale --nodaem ...   Up       0.0.0.0:32772->3306/tcp 
clustermaxscale_replication-manager_1   replication-manager monito ...   Exit 2     
~~~

Passing `--daemon=true` in the command serves as workarround.

**Comment by tanji** [comment]
@hugochinchilla I do not support anything that has been added to the contrib repository, as its name implies (probably got to add a disclaimer README for that, I reckon)
Feel free to post a PR if you think that should be fixed.
